comdb2/dbapi2.py
tests/test_dbapi2.py

We already blocked retrieving rows from a cursor when we've set `rowcount`, but we were still setting `description`.
This makes the behavior consistent, so that `description` is only set when we're exposing a result set that can be described.

Fix DB-API 2.0 description inconsistency

---

setup.py

comdb2 has a dependency on cython as part of its `setup_requires` but
`setup.py` is importing cython which makes it useless.
Since there is already a requirement for setup_tools >= 18.0 there is
no need to cythonise the code, as setuptools support cython.
It is actually more correct not to do it so the sdist will contain
the source cython files.
setup_tools works the issue around by deferring the use of cython after
the dependencies are resolved and installed.
This is an issue as users willing to install comdb2 need to have
cython already preinstalled in their system (before even the
requirement of setup_requires is read).
SOURCES from the resulting sdist generated after this change:
```
README.md
setup.py …
```

Remove use of cython at setup.py

---

setup.py

Even if the name of the repository is 'python-comdb2' there is no need
for the name of the Python package to be 'python-comdb2'. Should this be
distributed into a dpkg or anything outside of an 'only-python-packages'
system that package will probably well named 'python-comdb2'.
This package is not yet published into PyPI and any user who has locally
installed via `python setup.py install` will just see his files
overridden with the new package name. The change should be safe.

Proposal: Rename package to 'comdb2' from 'python-comdb2'

---

comdb2/__init__.py

Bump the minor version to reflect that the change to the package name is
backwards incompatible.  Given that this is unlikely to have any real
impact, since the package has never been published to PyPI, don't
increment the major version number.

Bump version to 1.2.0

---

setup.py

To allow `setup.py` to find the right location for headers and build the linkline, use pkg-config, as the underlying library provides a `.pc` file.

Use pkg-config to build the C extension

---

pyproject.toml
setup.py

Moving the dependencies here will allow us to install the project without using `easy-install` and allowing us to import `setup.py` without any extra dependency.
Depends on #11

 Use `pyproject.toml` for build dependencies

---

comdb2/__init__.py

As there is no functionality change, just a change on how we build the
sdist and therefore how it will be installed, bump the minor version
only.

Bump version to 1.2.1

---

MANIFEST.in

`setuptools` does not yet include `pyproject.toml` by default, include
it through the `MANIFEST.in` file.
Tested that the sdist includes pyproject.toml manually.

Add `MANIFEST.in` to include `pyproject.toml`

---

comdb2/_ccdb2.pyx

Replace Cython's deprecated `property` syntax with the property decorator.
I replaced the deprecated Cython `property` syntax, with the property decorator,
just like in the [Cython's docs](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#properties)

Replace Cython's deprecated `property` syntax

---

comdb2/_about.py

Bump the patch version for a new release that uses the modern Cython
`@property` decorator rather than the deprecated legacy syntax.

Bump version to 1.2.3

---

setup.py

We're meant to only list our direct dependencies here and let pkg-config
sort the rest out; this is a holdover from an earlier iteration when we
listed all dependencies directly.

setup.py: Drop explicit dependency on protobuf-c

---

docs/tips.rst

Passing a too-short byte array is a common mistake.
Signed-off-by: Ryan Hoban <rhoban@bloomberg.net>
Adding a note to tips

Add a note to tips about bytearray length

---

comdb2/_about.py

This is in preparation for a 1.3.0 release that includes a minor docs
improvement, a fix for SQL statements beginning with comments in
`dbapi2`, and a fix for building on machines where the `protobuf-c`
package is named `libprotobuf-c`.

Bump version to 1.3.0

---

comdb2/_ccdb2.pyx
tests/test_cdb2.py

When binding a parameter fails (usually because the provided value isn't
of an expected type), make the exception tell which parameter couldn't
be mapped and what type it has.

Improve error message for bind failures

---

comdb2/_cdb2_types.py

In Python 3, it's legal to call `datetime.datetime.astimezone` with no
arguments, in which case the system's local UTC offset is used for the
returned `datetime.datetime` object. Allow this to work for `DatetimeUs`
as well, by allowing it to be called with any number of arguments, and
forwarding them blindly along to `datetime.datetime` for validation.
Signed-off-by: Matt Wozniski <mwozniski@bloomberg.net>

Fix `DatetimeUs.astimezone` Python 3 compatibility

---

docs/conf.py

Sphinx 4.0 gives us this option, and allows us to avoid using a divisive
term with negative connotations.
Signed-off-by: Matt Wozniski <mwozniski@bloomberg.net>

Update to use `root_doc` instead of `master_doc`

---

comdb2/_about.py
comdb2/cdb2.pyi
comdb2/dbapi2.pyi

stubs: Type parameter dict's keys as Text
The `Mapping` type is invariant for the key, rather than covariant,
meaning that a `Mapping[Text, int]` isn't considered a subtype of
`Mapping[Union[Text, bytes], int]`, so these annotations were wrong.
To fix them, we'll say that the key must be `Text`.
For the DB-API 2.0 interface this makes no difference whatsoever,
because in Python 3 mode we already only accepted `Text`, and in Python
2 mode mypy accepts a `bytes` where a `Text` was expected.
For the `cdb2` submodule, this means that using `bytes` for the key in
Python 3 won't typecheck cleanly, even though it works. That seems like
a reasonable tradeoff: although it works, we'd prefer users use `str`
keys, so the warning if they don't seems reasonable.
Signed-off-by: Matt Wozniski …

Fix params type hints

---

.github/workflows/build.yml
pyproject.toml
setup.py
tests/schemas/mattdb/all_datatypes.csc2
tests/schemas/mattdb/child.csc2
tests/schemas/mattdb/simple.csc2
tests/schemas/mattdb/strings.csc2
tests/schemas/mattdb/table_constraint_order.txt
tests/test_cdb2.py
tests/test_dbapi2.py

Fixes #37
2 of the 95 tests do not pass because `cdb2_open` seems to completly ignore its third argument (and that is considered a bug by the maintainers of bloomberg/comdb2). These tests are not considered critical and thus we will be skipping them for now, while the people maintaining comdb2 find a solution on how to fix it.
Use Github Actions to run the tests automatically for every PR.
The tests are being run on Github Actions for this very PR.
**Additional context**
Note that https://github.com/bloomberg/comdb2/pull/3355 and https://github.com/bloomberg/comdb2/pull/3362 were merged specifically to enable this PR.

Enable CI on Github Actions

---

comdb2/cdb2.py
comdb2/dbapi2.py
docs/tips.rst
docs/types.rst

We were using `T` as a stand-in for any valid parameter type, but Sphinx
doesn't like that. Let's just use `Any` in the docs - the actual valid
types are spelled out in the type stubs, but adding them to the
documentation would make things unnecessarily verbose and repetitive.
Likewise, we were using `Row` as a stand-in for whatever row type is
configured using the `row_factory`, but let's just drop that and leave
it implicit.
Finally, use code formatting (double backticks) rather than references
(single backticks) for some things that were never meant to be
references.
Signed-off-by: Matt Wozniski <mwozniski@bloomberg.net>

docs: Fix Sphinx warnings

---

.github/workflows/build.yml
comdb2/_about.py
setup.py

- Remove `.pxd` source files
- Ensure CI is run daily to detect problems faster

Fix bug with Cython and make CI run daily

---

.github/workflows/build.yml
MANIFEST.in

#44 was closed when I (accidentally) force pushed to the branch, removing all commits that weren't on `main`… Re-opening as another PR because I don't have the privileges required to re-open #44.

Fix `MANIFEST.in` and make CI tests build and use a source distribution instead of the source directly

---

comdb2/__init__.py
comdb2/_about.py
comdb2/_ccdb2.pyx
comdb2/_cdb2_types.py
comdb2/cdb2.py
comdb2/dbapi2.py
comdb2/factories.py
docs/conf.py
docs/dbapi2.rst
docs/tips.rst
docs/types.rst
setup.py
tests/test_cdb2.py
tests/test_cdb2_datetimeus.py
tests/test_dbapi2.py

Drop support for 2.7, and bump version to be `1.5.0`, the first version that explicitly supports 3.6+

Drop 2.7 support

---

comdb2/__init__.py
comdb2/_about.py
setup.py

Change `python_requires` to make it explicit that this version only
supports 3.7+ and bump the minor version.
Note that `pyupgrade --py37-plus` is a no-op.
Signed-off-by: Gus Monod <gmonod1@bloomberg.net>

Drop support for 3.6

---

comdb2/_ccdb2.pyx
comdb2/_cdb2api.pxd
tests/test_dbapi2.py

*Issue number of the reported bug or feature request: #<number>*
Add the ability to parameter bind carrays in dbapi2 through python lists, or tuples of type: int, float. string or bytes.
This is by exposing the cdb2_bind_array function present in cdb2api.
Add pytests that try all combinations of accepted parameters. ie. lists and tuples of allowed data types.
**Additional context**
None.

Add Support for Parameter Binding Arrays

---

comdb2/_ccdb2.pyx

It'd be hard to trigger, and would require a race between threads, but this defends against the issue.

Fix a potential use-after-free bug

---

comdb2/cdb2.pyi

This update was missed when support for binding arrays was introduced.

Update type annotations to allow binding arrays

---

tests/test_cdb2_datetimeus.py

This test takes the current date and time and switches the year to a hardcoded one. On leap day, that fails because the hardcoded year didn't have a February 29th. Update the test to use a hardcoded year that did.

tests: Fix a test that fails on leap days

---

.github/workflows/build.yml

actions/checkout@v4 is getting a "permission denied" error when attempting to remove some of these files. Remove them ourselves as a super-user.

ci: Explicitly remove Comdb2 build artifacts

---

setup.py

This allows us to use the C++ standard library to more easily implement future changes, and reduces friction with some internal patches.

Begin building as C++ rather than C99

---

comdb2/dbapi2.py

Signed-off-by: Saharsh Rathi <srathi41@bloomberg.net>
Closes #70 
I have changed the typing of return type of fetchall and fetchmany from `collections.abc.Sequence` -> `typing.List`
No tests written. 
**Additional context**
Add any other context about your contribution here.

Declare `fetchmany` and `fetchall` to return lists instead of `Sequence`

---

.github/dependabot.yml
.github/workflows/build.yml

The latest version of each is v4, and v3 is deprecated and scheduled to be decommissioned.

Update `upload-artifact` and `download-artifact`

---

comdb2/_about.py
comdb2/_cdb2api.pxd

While `libcdb2api` itself is implemented in C, the version used
internally at Bloomberg can optionally call into some plugins that are
implemented in C++, which could raise exceptions.
Ensure that `python-comdb2` catches any such exceptions, both for the
benefit of Bloomberg's internal Comdb2 users and to guard against the
possibility that C++ code is added to `libcdb2api` itself in the future.

Handle C++ exceptions thrown within `libcdb2api`

---

comdb2/_about.py
comdb2/cdb2.py
comdb2/dbapi2.py

resolves #78 
`Value` type has been replaced by `ColumnValue` and `ParameterValue` types, both of which are exposed via both `cdb2.py` and `dbapi2.py` modules. Updated anything that uses the `Value` type to now use one of those two types.
Currently no tests. I could create a series of tests that look like below, but I'm not sure how value-added that is, since none of the other exports from any modules are similarly tested.
```python
def test_column_value_is_exported_from_dbapi2() -> None:
from comdb2.dbapi2 import ColumnValue
```
or I could build a test that creates a fake package that imports these types and then runs `mypy`, but again I'm not sure how value-added that is.
**Additional context**
Spoke with Matt about this change and he …

Export `Value` and `ParameterValue` type aliases

---

.github/workflows/build.yml
setup.py

CI has been upgraded to run on Ubuntu 24.04. Rather than pin to 22.04, get things working instead. This necessitates dropping support for Python 3.7, as `actions/setup-python` does not support Python 3.7 on Ubuntu 24.04.

Drop support for Python 3.7, and fix CI on Ubuntu 24.04

---

comdb2/_cdb2_types.py
tests/test_cdb2_datetimeus.py

Can be used to translate explictly the type where a subclass of datetimeus is not accepted (such as pydantic).
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>

Add asdatetime helper to DatetimeUs

---

docs/conf.py

This is now triggering warnings saying that:
WARNING: The config value `viewcode_import' has type `bool';
expected `NoneType'.
The comment says that we were trying to prevent the `viewcode` extension from generating HTML for the standard library `datetime` module, but even with this setting removed it doesn't do that. This may just be a holdover from some long ago version of Sphinx, but it no longer seems to be necessary or useful.

docs: Remove an unused setting from docs/conf.py

---

comdb2/_ccdb2.pyx
comdb2/_cdb2api.pxd
comdb2/cdb2.py
comdb2/dbapi2.py
docs/tips.rst
tests/test_cdb2.py
tests/test_dbapi2.py

*Issue number of the reported bug or feature request: #82 *
Added support for binding by index by using a sequence of parameter values. Also checks if the value provided in this case is an array, which is not supported.
Examples:
`handle.execute("select ?", [10])`
This would output `10`
NOTE: when binding by index `%` does not need to be escaped in dbapi2. In all other cases using dbapi2 (even if not parameter binding), `%` needs to be escaped
https://peps.python.org/pep-0249/#id53 supports using a sequence of values with qmark param style
cdb2:
Added test to make sure binding an array by index does not work.
Added test that inserts parameters binded by index, similar to test that inserts parameters binded by value.
dbapi2:
Tested different …

Add support for binding parameters by index

---

.github/workflows/build.yml
tests/test_dbapi2.py

Add Python 3.14 support and fix `test_date_column_decode_exception` to handle updated datetime year validation error messages.
In Python 3.14, the error changed from `"year 0 is out of range"` to `"year must be in MINYEAR..MAXYEAR, not 0" `([CPython change](https://github.com/python/cpython/commit/3e222e3a15959690a41847a1177ac424427815e5#diff-3ee250e3806e884518fd872e9148baf532de6ec54c1cdb4e7679fbb2869d9c47)). The test now accepts both formats for compatibility across Python versions.

Add Python 3.14 support
